server:
  port: 8989
spring:
  jpa:
    hibernate:
      ddl-auto: update # in dev create, in prod this should be update
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
  datasource:
    url: jdbc:h2:file:./app

